const fish_spots = {
    "bluefin-tuna": [
      "Around Lady Julia Percy Island",
      "Offshore Mallacoota",
      "Seal Island group"
    ],
    "gurnard": [
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance"
    ],
    "leatherjacket": [
      "Black Rock pier",
      "Rocks at West Head"
    ],
    "luderick": [
      "Bridge linking Ocean Grove to Barwon Heads",
      "Bullock Island",
      "Captains Point",
      "Devils Hole",
      "Entrance Channel",
      "Fishermen's Jetty",
      "Florence Bay",
      "Hopkins River estuary",
      "Jemmys Point",
      "Jetty at Kalimna",
      "Mallacoota boat ramp",
      "McLennan Strait leading to Lake Wellington",
      "Moyne River estuary",
      "Near entrance to Sydenham Inlet",
      "Nicholson River entrance and upstream",
      "Ozone Jetty",
      "Reeve Channel off Flannagan Island",
      "Snowy River - inlet and adjacent estuaries",
      "Tambo River"
    ],
    "estuary-perch": [
      "Anglesea River",
      "Barham River upstream",
      "Bass River",
      "Bemm River",
      "Betka River estuary and upstream",
      "Erskine River - lower reaches",
      "Genoa River",
      "Glenelg River estuary",
      "Hopkins River estuary",
      "Marlo ramp  jetty",
      "McLennan Strait leading to Lake Wellington",
      "Nicholson River entrance and upstream",
      "Painkalac Creek",
      "Snowy River - inlet and adjacent estuaries",
      "Tamboon Inlet",
      "Tarwin River",
      "The Back Water",
      "Wallagaraugh River",
      "Yeerung River estuary"
    ],
    "elephant-fish": [
      "East Arm - Tortoise Head to Corinlella"
    ],
    "king-george-whiting": [
      "10 kms off Kirk Point",
      "18m line Mt Martha to Mt Eliza",
      "2 to 3 kms from Werribee River mouth",
      "Aireys Inlet \u2013 Eagle Rock",
      "Anderson Inlet",
      "Anderson Inlet entrance",
      "Anonyma Shoal off Half Moon Bay, Sandringham",
      "Around Portland",
      "Arthur the Great buoy",
      "Artillery Rocks",
      "Avalon to Point Wilson",
      "Balnarring Beach to Flinders",
      "Beaumaris Yacht Squadron Pier",
      "Bennison Channel (part in proposed park)",
      "Between South Channel Pile and South Channel Fort",
      "Blacknose Point",
      "Bouchier Channel",
      "Boulton Channel",
      "Brighton Breakwall and Pier",
      "Campbell Channel",
      "Capel Sound",
      "Cat Bay",
      "Channel north of Sunday Island",
      "Channels near McLoughlins Beach",
      "Channels near Port Albert entrance",
      "Channels off Rhyll",
      "Channels on eastern side of Western Port",
      "Coastal rock platforms Kennett River to Skenes Creek",
      "Cockyanes Channel",
      "Corinella Channel",
      "Doughboy Channel",
      "Duck Point Channel",
      "Eastern View",
      "Edwards Point and Duck Island east of Swan Bay",
      "Elliott River",
      "Entrance to the Avon River, Lake Wellington",
      "Foreshores of river inlets at Tooradin and Warneet",
      "Gardiners and Blakes channels (near French Island)",
      "Gentle Anne Channel",
      "Hayley Reef off Marengo",
      "Head of Corio Bay and around shipping channel",
      "Hopetoun Channel",
      "Ingoldsby",
      "Kerferd Road Pier - 900m out (\u2018The Magpie\u2019)",
      "Killarney Beach",
      "Lady Bay Breakwater",
      "Lewis Channel off Port Welshpool",
      "Lonsdale Bay (part)",
      "Lyalls Channel",
      "Manns Beach",
      "Marengo Beach",
      "McLennan Strait leading to Lake Wellington",
      "Middle Channel",
      "Mornington Pier",
      "Mosquito and Elizabeth Channels",
      "Mounts Bay",
      "Mud Islands",
      "Nathan's Point",
      "Near Torquay boat ramp",
      "Near entrance to Sydenham Inlet",
      "North Arm, Shipping Channel",
      "Northern Bay sand flats",
      "Out from Cowes Piew (meeting of North and East Arms)",
      "Parker River",
      "Peterborough Bay",
      "Point Cook RAAF Jetty",
      "Point Cook into Altona Bay",
      "Point Danger",
      "Point Grey",
      "Point Henry",
      "Point Lonsdale Pier",
      "Port Campbell Bay channel",
      "Port Campbell jetty",
      "Port Welshpool jetties",
      "Portarlington Pier",
      "Portarlington to Queenscliff",
      "Portsea to Sorrento, including Portsea and Sorrento piers",
      "Prince George Light off Grassy Point",
      "Reeve Channel off Flannagan Island",
      "Retaining wall between Western Beach boatsheds and Cunningham Pier",
      "Rippleside Jetty, Geelong",
      "Robertsons Beach",
      "Rocks at West Head",
      "Rocks near Point Lillias",
      "Shallow Inlet",
      "Shaving Point",
      "She-oak Creek, south-west of Lorne",
      "Somers to Balnarring Beach",
      "South Channel",
      "St Leonards Pier",
      "Stockyard Channel",
      "Swan Bay (part)",
      "Table Rock, Beaumaris Bay",
      "Tamboon Inlet",
      "The Cutting to Killarney Beach",
      "Toora Channel",
      "Tooradin Channel",
      "Walker Point",
      "Waratah Bay",
      "Werribee River to Wedge Point",
      "Western Port North - Inside Channel",
      "Western Port North - Post Office gutter",
      "Wilson Point"
    ],
    "long-finned-pike": [
      "Annabella Reef",
      "Around Lawrence Rocks",
      "Bennison Channel (part in proposed park)",
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Doughboy Channel",
      "Ingoldsby",
      "Manns Beach",
      "Middle Channel",
      "Port Welshpool jetties",
      "Robertsons Beach",
      "Rocks at West Head",
      "Stockyard Channel",
      "Thunder Point",
      "Toora Channel"
    ],
    "flathead": [
      "2 to 3 kms from Werribee River mouth",
      "Around Portland",
      "Aurora Channel opposite Raymond Island",
      "Bancroft Bay",
      "Beaumaris Yacht Squadron Pier",
      "Bemm River",
      "Bennison Channel (part in proposed park)",
      "Betka River estuary and upstream",
      "Boat harbour at Apollo Bay",
      "Bouchier Channel",
      "Boulton Channel",
      "Brighton Breakwall and Pier",
      "Campbell Channel",
      "Cape Conran",
      "Cape Horn",
      "Capel Sound",
      "Cemetery Bight",
      "Channel north of Sunday Island",
      "Channels near McLoughlins Beach",
      "Channels near Port Albert entrance",
      "Channels off Rhyll",
      "Cockyanes Channel",
      "Devils Hole",
      "Doughboy Channel",
      "Dromana Bay",
      "Dromana Pier",
      "Duck Arm",
      "Duck Point Channel",
      "Edwards Point and Duck Island east of Swan Bay",
      "Entrance to the Avon River, Lake Wellington",
      "Fisherman's Landing Arm",
      "Florence Bay",
      "Gordon Bight to Big Bight, Nowa Nowa Arm",
      "Jetty at Kalimna",
      "John Bull Light",
      "Lagoon Pier",
      "Limeburners Bay",
      "Lyalls Channel",
      "Manns Beach",
      "Marlo ramp  jetty",
      "McLennan Strait leading to Lake Wellington",
      "Metung to Tambo Bluff",
      "Middle Channel",
      "Mornington Pier",
      "Mud Islands",
      "North Arm, Shipping Channel",
      "Offshore Mallacoota",
      "Outside the entrance, Portsea to Flinders coastline surf fishing from Portsea Surf Beach, Rye Ocean Beach, Gunnamatta and St. Andrews",
      "Past Hayley Reef",
      "Paynesville",
      "Perserverance wreck",
      "Picnic Arm",
      "Point Cook into Altona Bay",
      "Point Henry",
      "Port Welshpool jetties",
      "Portarlington Pier",
      "Portsea Hole (about 1 km out from Portsea Pier)",
      "Portsea to Sorrento, including Portsea and Sorrento piers",
      "Princes Pier",
      "Red Point, Cape Woolamai",
      "Reeve Channel off Flannagan Island",
      "Retaining wall between Western Beach boatsheds and Cunningham Pier",
      "Robertsons Beach",
      "Sandridge Beach",
      "Shallow Inlet",
      "Shaving Point",
      "Shoreline to Steel Bay",
      "Snowy River mouth - surf",
      "Snowy River mouth, Frenchs Narrows",
      "St Kilda Pier",
      "Station Pier",
      "Stockyard Channel",
      "Surf fishing beaches",
      "Swan Bay (part)",
      "Table Rock, Beaumaris Bay",
      "Tambo Bluff",
      "Tambo River",
      "Tamboon Inlet",
      "Target buoy area offshore from the RAAF Jetty",
      "Toora Channel",
      "Toorloo Arm upstream towards Burnt Bridge",
      "Top Lake",
      "Waratah Bay",
      "West of Mud Islands",
      "Western Port North - Inside Channel"
    ],
    "flounder": [
      "Bennison Channel (part in proposed park)",
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Doughboy Channel",
      "Dromana Bay",
      "Limeburners Bay",
      "Loch Sport and jetty",
      "Middle Channel",
      "Port Welshpool jetties",
      "South Channel",
      "Stockyard Channel",
      "Toora Channel"
    ],
    "mullet": [
      "Aireys Inlet - near lighthouse",
      "Anglesea River",
      "Back beaches of Anderson Inlet  Venus Bay",
      "Bancroft Bay",
      "Bass River",
      "Bennison Channel (part in proposed park)",
      "Black Rock pier",
      "Bouchier Channel",
      "Boulton Channel",
      "Brighton Breakwall and Pier",
      "Butchers Jetty",
      "Campbells Creek",
      "Carisbrook Creek",
      "Channel below Bullock Island bridge",
      "Cockyanes Channel",
      "Cumberland River estuary",
      "Curdies River at Peterborough",
      "Doughboy Channel",
      "Eastern Ocean Beach south of Cunninghame Arm causeway",
      "Entrance Channel",
      "Erskine River - lower reaches",
      "Fisherman's Landing jetty",
      "Fitzroy River",
      "Foreshores of river inlets at Tooradin and Warneet",
      "Gem Pier \u2013 Williamstown",
      "Glenelg River estuary",
      "Gordon Bight to Big Bight, Nowa Nowa Arm",
      "Hopkins River estuary",
      "Jetties in Cunninghame Arm",
      "Jetty at Kalimna",
      "Kennett River",
      "Lagoon Pier",
      "Levys Beach",
      "Limeburners Bay",
      "Loch Sport and jetty",
      "Logans Beach",
      "Lorne Pier",
      "Lyalls Channel",
      "Marlo ramp  jetty",
      "McLennan Strait leading to Lake Wellington",
      "Middle Channel",
      "Mordialloc Pier",
      "Moyne River estuary",
      "Ninety Mile Beach adjacent to Lake Tyers",
      "O'Brien's Point",
      "Outside the entrance, Portsea to Flinders coastline surf fishing from Portsea Surf Beach, Rye Ocean Beach, Gunnamatta and St. Andrews",
      "Patterson River entrance",
      "Point Lonsdale Pier",
      "Port Welshpool jetties",
      "Princes Pier",
      "Princetown",
      "Queenscliff Pier",
      "Skenes Creek",
      "St George River estuary",
      "St Kilda Pier",
      "Station Pier",
      "Stockyard Channel",
      "Surrey River",
      "Toora Channel",
      "Wild Dog Creek",
      "Wye River estuary",
      "Yambuk Lake",
      "Yeerung River estuary",
      "\u201cWarmies\u201d at Newport power station"
    ],
    "marlin": [
      "Offshore Mallacoota"
    ],
    "brown-trout": [
      "Barham River upstream"
    ],
    "australian-salmon": [
      "Aireys Inlet - near lighthouse",
      "Aireys Inlet \u2013 Eagle Rock",
      "Anderson Inlet",
      "Anglesea River",
      "Anonyma Shoal off Half Moon Bay, Sandringham",
      "Artillery Rocks",
      "Back beaches of Anderson Inlet  Venus Bay",
      "Beach east side of Aire River",
      "Bell Reef at Shortland Bluff, Queenscliff",
      "Bennison Channel (part in proposed park)",
      "Boat harbour at Apollo Bay",
      "Breakwater",
      "Bridge linking Ocean Grove to Barwon Heads",
      "Bullock Island",
      "Campbell Channel",
      "Cape Conran",
      "Carisbrook Creek",
      "Castle Cove",
      "Centre of Lake Victoria",
      "Channel north of Sunday Island",
      "Channel past Fairhaven Life Saving Club",
      "Channels near Port Albert entrance",
      "Channels on eastern side of Western Port",
      "Coastal rock platforms Kennett River to Skenes Creek",
      "Cumberland River estuary",
      "Curdies River at Peterborough",
      "Discovery Bay",
      "Discovery Bay at Cape Bridgewater",
      "Doughboy Channel",
      "Eastern Ocean Beach south of Cunninghame Arm causeway",
      "Eastern View",
      "Either side of entrance to Mallacoota Inlet",
      "Elliott River",
      "Entrance Channel",
      "Erskine River - lower reaches",
      "Explosives Pier",
      "Fishermen's Jetty",
      "Fitzroy River",
      "Fitzroy River beach",
      "Gabo Island",
      "Gibsons Steps",
      "Head of Corio Bay and around shipping channel",
      "Hutt Gully",
      "Ingoldsby",
      "Jetty at Kalimna",
      "Johanna surf beach",
      "Kennett River",
      "Killarney Beach",
      "Kitty Miller Bay Beach",
      "Levys Beach",
      "Logans Beach",
      "Lorne Pier",
      "Loutit Bay",
      "Manns Beach",
      "Middle Channel",
      "Moggs Creek",
      "Mounts Bay",
      "Mouth of Betka River",
      "Moyne River estuary",
      "Narrawong beach",
      "Nathan's Point",
      "Near entrance to Sydenham Inlet",
      "Ninety Mile Beach adjacent to Lake Tyers",
      "Outside the entrance, Portsea to Flinders coastline surf fishing from Portsea Surf Beach, Rye Ocean Beach, Gunnamatta and St. Andrews",
      "Ozone Jetty",
      "Parker River",
      "Patterson River entrance",
      "Point Lonsdale Pier",
      "Princetown",
      "Red Point, Cape Woolamai",
      "Robertsons Beach",
      "Shallow Inlet",
      "She-oak Creek, south-west of Lorne",
      "Skenes Creek",
      "Snowy River mouth - surf",
      "South coast of Snake Island off Bentley Point",
      "St George River estuary",
      "Stockyard Channel",
      "Surf beach at mouth to Sydenham Inlet",
      "Surrey River",
      "The Cutting to Killarney Beach",
      "The Narrows",
      "The Rip",
      "Toora Channel",
      "Tullaberga Island",
      "Urquhart Bluff",
      "Waratah Bay",
      "Water off Point Nepean adjacent to Mornington Peninsula National Park",
      "Wild Dog Creek",
      "Wye River estuary",
      "Yambuk"
    ],
    "barracouta": [
      "Apollo Bay jetties",
      "Boat harbour at Apollo Bay",
      "Jetty at Kalimna",
      "Lorne Pier",
      "Point Lonsdale Pier",
      "Red Point, Cape Woolamai",
      "Shallow Inlet",
      "Waratah Bay"
    ],
    "bass": [
      "Bemm River",
      "Genoa River",
      "Snowy River - inlet and adjacent estuaries",
      "The Back Water",
      "Wallagaraugh River"
    ],
    "bream": [
      "Anglesea River",
      "Around eastern end of Rigby Island",
      "Aurora Channel opposite Raymond Island",
      "Bancroft Bay",
      "Barham River upstream",
      "Bass River",
      "Bemm River",
      "Betka River estuary and upstream",
      "Bobs Bay",
      "Breakwater",
      "Bridge linking Ocean Grove to Barwon Heads",
      "Bullock Island",
      "Butchers Jetty",
      "Campbell Channel",
      "Campbells Creek",
      "Cape Horn",
      "Carisbrook Creek",
      "Channel below Bullock Island bridge",
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Curdies River at Peterborough",
      "Devils Hole",
      "Double Creek Arm",
      "Duck Arm",
      "Eastern side of Bell Point under the cliffs",
      "Entrance Channel",
      "Entrance to the Avon River, Lake Wellington",
      "Erskine River - lower reaches",
      "Fisherman's Landing Arm",
      "Fishermen's Jetty",
      "Fitzroy River",
      "Florence Bay",
      "Gem Pier \u2013 Williamstown",
      "Genoa River",
      "Glenelg River estuary",
      "Gordon Bight to Big Bight, Nowa Nowa Arm",
      "Hollands Landing",
      "Hopkins River estuary",
      "Jetties in Cunninghame Arm",
      "Jetty at Kalimna",
      "John Bull Light",
      "Kennett River",
      "Lagoon Pier",
      "Limeburners Bay",
      "Loch Sport and jetty",
      "Marlo ramp  jetty",
      "McLennan Strait leading to Lake Wellington",
      "Metung to Tambo Bluff",
      "Mitchell River",
      "Moggs Creek estuary",
      "Mordialloc Pier",
      "Mouth of Maringa Creek",
      "Moyne River estuary",
      "Near entrance to Sydenham Inlet",
      "Nicholson River entrance and upstream",
      "Ninety Mile Beach adjacent to Lake Tyers",
      "O'Brien's Point",
      "Ozone Jetty",
      "Painkalac Creek",
      "Paynesville",
      "Pelican Point",
      "Picnic Arm",
      "Princes Pier",
      "Princetown",
      "Reeve Channel off Flannagan Island",
      "Retaining wall between Western Beach boatsheds and Cunningham Pier",
      "Rocks near Point Lillias",
      "Shoreline to Steel Bay",
      "Skenes Creek",
      "Snowy River - inlet and adjacent estuaries",
      "St Kilda Pier",
      "Station Pier",
      "Surrey River",
      "Tambo Bluff",
      "Tambo River",
      "Tamboon Inlet",
      "Tarwin River",
      "The Mahoganys",
      "Toorloo Arm upstream towards Burnt Bridge",
      "Top Lake",
      "Under West Gate Bridge",
      "Upstream Glenelg River",
      "Walker Point",
      "Wallagaraugh River",
      "Werribee River estuary",
      "Wild Dog Creek",
      "Wilson Point",
      "Wye River estuary",
      "Yambuk Lake",
      "Yeerung River estuary",
      "\u201cWarmies\u201d at Newport power station"
    ],
    "school-shark": [
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Glenelg River mouth",
      "Point Lonsdale Pier",
      "Portland Harbour to Fitzroy River"
    ],
    "snook": [
      "Annabella Reef",
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Ingoldsby",
      "Manns Beach",
      "Mills Reef",
      "North Arm, Shipping Channel",
      "Robertsons Beach",
      "Seal Island group",
      "South coast of Snake Island off Bentley Point",
      "Thunder Point"
    ],
    "squid": [
      "Cat Bay",
      "St Leonards Pier"
    ],
    "sweep": [
      "Annabella Reef",
      "Around Lady Julia Percy Island",
      "Around Lawrence Rocks",
      "Cape Nelson",
      "Cape Sir William Grant",
      "Discovery Bay at Cape Bridgewater",
      "Lee Breakwater",
      "Mills Reef",
      "Point Danger",
      "Rifle Butts",
      "Thunder Point"
    ],
    "pinkie-snapper": [
      "1 km off Blairgowrie (Shark Hole)",
      "10 kms off Kirk Point",
      "18m line Mt Martha to Mt Eliza",
      "6km offshore",
      "Aireys Inlet \u2013 1 km out from lighthouse",
      "Aireys Inlet \u2013 Eagle Rock",
      "Anderson Inlet",
      "Anderson Inlet entrance",
      "Anonyma Shoal off Half Moon Bay, Sandringham",
      "Ansetts",
      "Aquarium hole \u2013 800m off Black Rock",
      "Around Lady Julia Percy Island",
      "Around Portland",
      "Around Williamstown",
      "Arthur the Great buoy",
      "Artillery Rocks",
      "Aspendale opposite CSIRO beacon",
      "Beach east side of Aire River",
      "Beaumaris Yacht Squadron Pier",
      "Bellarine Bank",
      "Bennison Channel (part in proposed park)",
      "Between Bullock and Rigby Islands",
      "Bouchier Channel",
      "Boulton Channel",
      "Breakwater",
      "Breakwater Pier",
      "Brighton Breakwall and Pier",
      "CSIRO beacon",
      "Capel Sound",
      "Carrum Drain offshore",
      "Castle Cove",
      "Cat Bay",
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Channels on eastern side of Western Port",
      "Coastal rock platforms Kennett River to Skenes Creek",
      "Cockyanes Channel",
      "Cod Splat",
      "Corinella Channel",
      "Corvette Hole",
      "Crawfish Rock",
      "Discovery Bay",
      "Discovery Bay at Cape Bridgewater",
      "Doughboy Channel",
      "Eastern View",
      "Elliott River",
      "Explosives Pier",
      "Fawkner Beacon \u2013 5 km off Sandringham Breakwater",
      "Fitzroy River beach",
      "Franklin Channel",
      "Gardiners and Blakes channels (near French Island)",
      "Gellibrand shoal",
      "Gibsons Steps",
      "Glenelg River mouth",
      "Head of Corio Bay and around shipping channel",
      "Helens Rock",
      "Hovel Pile, off Rosebud",
      "Hutt Gully",
      "Ingoldsby",
      "Jetty at Kalimna",
      "Joe's Island",
      "John Bull Light",
      "Kerferd Road Pier - 900m out (\u2018The Magpie\u2019)",
      "Killarney Beach",
      "Lee Breakwater",
      "Limeburners Bay",
      "Loelia channel",
      "Lonsdale Bay (part)",
      "Loutit Bay",
      "Lyalls Channel",
      "Metung to Tambo Bluff",
      "Middle Channel",
      "Minerva Reef",
      "Moggs Ledge",
      "Mordialloc to Frankston",
      "Mornington Pier",
      "Morrisons Fault Line, 2 km from Linley Point and stretching to Martha Cliffs, Mount Martha",
      "Mosquito and Elizabeth Channels",
      "Mud Islands",
      "Narrawong beach",
      "Nathan's Point",
      "Near Torquay boat ramp",
      "Near entrance to Sydenham Inlet",
      "North Arm, Shipping Channel",
      "Northern Bay sand flats",
      "Ocean Grove - surf",
      "Off McHaffief Point",
      "Off Surrey River mouth 400 - 500m out",
      "Offshore Mallacoota",
      "Offshore from White Crests Guest House",
      "Out from Cowes Piew (meeting of North and East Arms)",
      "Out from piers of Port Melbourne (\u2018Siberia\u2019)",
      "Outer Artificial Reef out from Carrum Drain",
      "P2 Buoy",
      "Parker River",
      "Perserverance wreck",
      "Pinnace Channel",
      "Point Cook RAAF Jetty",
      "Point Henry",
      "Point Lillias",
      "Port Campbell Bay channel",
      "Port Campbell jetty",
      "Portarlington Pier",
      "Portsea Hole (about 1 km out from Portsea Pier)",
      "Portsea to Sorrento, including Portsea and Sorrento piers",
      "Prince George Light off Grassy Point",
      "Reef 1.5 km off Cape Patton",
      "Reef off Basin Point",
      "Retaining wall between Western Beach boatsheds and Cunningham Pier",
      "Ricketts Point \u2013 Quiet Corner",
      "Rocks near Point Lillias",
      "Seaford Pier offshore",
      "Seal Island group",
      "She-oak Creek, south-west of Lorne",
      "Shelly Beach west of Portland",
      "Singapore Deep",
      "South coast of Snake Island off Bentley Point",
      "Spoil Ground",
      "St Leonards Pier",
      "Stockyard Channel",
      "Symonds channel",
      "Table Rock, Beaumaris Bay",
      "Tambo Bluff",
      "Tamboon Inlet",
      "Target buoy area offshore from the RAAF Jetty",
      "The Basket beacon",
      "The Narrows",
      "The Rip",
      "Toora Channel",
      "Torquay",
      "Under West Gate Bridge",
      "Werribee River to Wedge Point",
      "Western Port North - Post Office gutter",
      "Yambuk",
      "\u2018Outer Spuds\u2019 \u2013 3 km off Brighton Pier"
    ],
    "garfish": [
      "Bancroft Bay",
      "Black Rock pier",
      "Brighton Breakwall and Pier",
      "Coastal rock platforms Kennett River to Skenes Creek",
      "Dendy Street shallows",
      "Double Creek Arm",
      "Elliott River",
      "Fisherman's Landing Arm",
      "Fisherman's Landing jetty",
      "Gordon Bight to Big Bight, Nowa Nowa Arm",
      "Lady Bay Breakwater",
      "Lagoon Pier",
      "Lorne Pier",
      "Mornington Pier",
      "Parker River",
      "Point Grey",
      "Port Welshpool jetties",
      "Portarlington Pier",
      "Princes Pier",
      "Rifle Butts",
      "Rippleside Jetty, Geelong",
      "St Kilda Pier",
      "Station Pier",
      "Toorloo Arm upstream towards Burnt Bridge"
    ],
    "mulloway": [
      "Beach east side of Aire River",
      "Between Bullock and Rigby Islands",
      "Between Flat Rock and McEacherns Rocks",
      "Bridge linking Ocean Grove to Barwon Heads",
      "Cape Horn",
      "Discovery Bay",
      "Discovery Bay at Cape Bridgewater",
      "Fishermen's Jetty",
      "Glenelg River estuary",
      "Glenelg River mouth",
      "Hopkins River estuary",
      "McLennan Strait leading to Lake Wellington",
      "Mouth of the Yarra",
      "Moyne River estuary",
      "Narrawong beach",
      "Near entrance to Sydenham Inlet",
      "Ocean Grove - surf",
      "Off Surrey River mouth 400 - 500m out",
      "Ozone Jetty",
      "Snowy River mouth - surf",
      "Surf fishing beaches",
      "Tambo River",
      "The Narrows",
      "Under West Gate Bridge",
      "\u201cWarmies\u201d at Newport power station"
    ],
    "silver-trevally": [
      "Anderson Inlet",
      "Anglesea River",
      "Apollo Bay jetties",
      "Around Lady Julia Percy Island",
      "Back beaches of Anderson Inlet  Venus Bay",
      "Bell Reef at Shortland Bluff, Queenscliff",
      "Bennison Channel (part in proposed park)",
      "Boat harbour at Apollo Bay",
      "Bridge linking Ocean Grove to Barwon Heads",
      "Campbell Channel",
      "Channel north of Sunday Island",
      "Channels near Port Albert entrance",
      "Doughboy Channel",
      "Edwards Point and Duck Island east of Swan Bay",
      "Entrance Channel",
      "Erskine River - lower reaches",
      "Fishermen's Jetty",
      "Helens Rock",
      "Hutt Gully",
      "Jetty at Kalimna",
      "Killarney Beach",
      "Kitty Miller Bay Beach",
      "Lonsdale Bay (part)",
      "Lorne Pier",
      "Middle Channel",
      "Mounts Bay",
      "Moyne River estuary",
      "Near entrance to Sydenham Inlet",
      "Offshore from White Crests Guest House",
      "Ozone Jetty",
      "Port Campbell jetty",
      "Port Welshpool jetties",
      "Rocks near Point Lillias",
      "Shallow Inlet",
      "Stockyard Channel",
      "Swan Bay (part)",
      "Tamboon Inlet",
      "Toora Channel",
      "Western Port North - Inside Channel",
      "Yeerung River estuary"
    ],
    "prawns": [
      "Channels near McLoughlins Beach",
      "Snowy River - inlet and adjacent estuaries"
    ],
    "tailor": [
      "Bullock Island",
      "Campbell Channel",
      "Cape Conran",
      "Centre of Lake Victoria",
      "Channel below Bullock Island bridge",
      "Either side of entrance to Mallacoota Inlet",
      "Entrance Channel",
      "Fisherman's Landing jetty",
      "Gabo Island",
      "Gordon Bight to Big Bight, Nowa Nowa Arm",
      "Jetty at Kalimna",
      "Loch Sport and jetty",
      "Metung to Tambo Bluff",
      "Mouth of Betka River",
      "Near entrance to Sydenham Inlet",
      "Ninety Mile Beach adjacent to Lake Tyers",
      "Shallow Inlet",
      "Surf beach at mouth to Sydenham Inlet",
      "Surf fishing beaches",
      "Tambo Bluff",
      "Tullaberga Island",
      "West of Mud Islands",
      "\u201cWarmies\u201d at Newport power station"
    ],
    "thresher-shark": [
      "Helens Rock"
    ],
    "yelloweye-mullet": [
      "The Cutting to Killarney Beach"
    ],
    "bronze-whaler-shark": [
      "Joe's Island"
    ],
    "gummy-shark": [
      "Beach east side of Aire River",
      "Bennison Channel (part in proposed park)",
      "Bouchier Channel",
      "Boulton Channel",
      "Cape Conran",
      "Channel north of Sunday Island",
      "Channel past Fairhaven Life Saving Club",
      "Channels near Port Albert entrance",
      "Channels on eastern side of Western Port",
      "Cockyanes Channel",
      "Coles Channel light on the Swan Island Point",
      "Crawfish Rock",
      "Discovery Bay",
      "Discovery Bay at Cape Bridgewater",
      "Doughboy Channel",
      "Eastern Ocean Beach south of Cunninghame Arm causeway",
      "Fitzroy River beach",
      "Gabo Island",
      "Gibsons Steps",
      "Joe's Island",
      "Loutit Bay",
      "Lyalls Channel",
      "Middle Channel",
      "North Arm, Shipping Channel",
      "Ocean Grove - surf",
      "Offshore Mallacoota",
      "Portsea Hole (about 1 km out from Portsea Pier)",
      "Stockyard Channel",
      "Surf beach at mouth to Sydenham Inlet",
      "Toora Channel",
      "Tullaberga Island"
    ],
    "mackerel": [
      "Apollo Bay jetties"
    ],
    "morwong": [
      "Around Lady Julia Percy Island"
    ],
    "warehou": [
      "Apollo Bay jetties",
      "Around Lady Julia Percy Island"
    ],
    "yellowtail-kingfish": [
      "Annabella Reef",
      "Anonyma Shoal off Half Moon Bay, Sandringham",
      "Around Lady Julia Percy Island",
      "Around Lawrence Rocks",
      "Cape Nelson",
      "Cape Sir William Grant",
      "Gabo Island",
      "Helens Rock",
      "Ingoldsby",
      "Lonsdale Bay (part)",
      "Mills Reef",
      "Portsea Pier - outside anchor restriction zone",
      "Reef off Basin Point",
      "Seal Island group",
      "South coast of Snake Island off Bentley Point",
      "Thunder Point",
      "Tullaberga Island"
    ]
  };
  
  export default fish_spots;